###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-08-08 11:12:48
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-08-08 14:30:07
###############################################################

invokables:
	body_left_main_template : Body/Left/Template/BodyLeftMainTemplate
	body_left_logo_template : Body/Left/Template/BodyLeftLogoTemplate
	body_right_main_template : Body/Left/Template/BodyRightMainTemplate
	body_right_header_template : Body/Left/Template/BodyRightHeaderTemplate
	body_cover_main_template : Body/Cover/Template/BodyCoverMainTemplate
	body_right_breadcrum_template : Body/Right/Template/BodyRightBreadcrumTemplate
	body_base_main_template : Body/Base/Template/BodyBaseMainTemplate
shared :
	body_right_main_template : true